# Generated by Django 4.0.4 on 2022-05-05 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0002_tutor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='thumbnail',
        ),
    ]
